checkpoints:
  - display_name: LAB Room
    id: 0
    name: lab_room
    orientation:
      w: 0.205588
      x: 0.0
      y: 0.0
      z: 0.978639
    position:
      x: -0.0202527
      y: -0.00167704
      z: 0.0
# Setting estimate pose: Frame:map, Position(-0.59638, 0.568052, 0), Orientation(0, 0, 0.97913, 0.203235) = Angle: 2.73227
  - display_name: Elevator
    id: 1
    name: elevator
    orientation:
      w: 0.980573
      x: 0.0
      y: 0.0
      z: -0.196155
    position:
      x: -4.14317
      y: 6.6751
      z: 0.0
  - display_name: Meeting Room (E6.3)
    id: 2
    name: meeting_room_e6_3
    orientation:
      w: 0.982046
      x: 0.0
      y: 0.0
      z: -0.188643
    position:
      x: 3.19687
      y: 17.2911
      z: 0.0
  - display_name: Dean's Room
    id: 3
    name: dean_room
    orientation:
      w: 0.978820
      x: 0.0
      y: 0.0
      z: -0.204722
    position:
      x: 5.02712
      y: 23.8103
      z: 0.0
frame_id: map