checkpoints:
  - display_name: Meeting Room (E1.1)
    id: 0
    name: meeting_room_e1_1
    orientation:
      w: 0.997132
      x: 0.0
      y: 0.0
      z: 0.0756878
    position:
      x: -15.2248
      y: -2.85956
      z: 0.0
  - display_name: Elevator
    id: 1
    name: elevator
    orientation:
      w: 0.772493
      x: 0.0
      y: 0.0
      z: -0.635023
    position:
      x: -8.43639
      y: 2.17993
      z: 0.0
  - display_name: CELUiT's Office
    id: 3
    name: celuit_office
    orientation:
      w: 0.667696
      x: 0.0
      y: 0.0
      z: 0.744434
    position:
      x: 6.51049
      y: -0.00394517
      z: 0.0
frame_id: map